<ScreenVideoView>:
  name: "screen_video"
  md_bg_color: "#67AB9F"
  FloatLayout:    

    Image:
      source: 'images/flower_background.png'
      size_hint: (None, None)
      size: "200dp", "200dp"
      pos_hint: {"center_x": 0.5, "center_y": 0.5}

    ScrollView:
      # pos_hint: {"center_x": 0.5, "center_y": 0.5}
      MDList:
        id: list_video
        pos_hint: {"center_x": 0.5, "center_y": 0.5}